### ISSUE TITLE
Names with spaces fail and dates no longer compare correctly

### ISSUE THREAD

**Issue by HieiOne** [alex13lopez/gcloud-backup#11]
If the folder or filename have spaces the upload fails. Fix soon

**Comment by alex13lopez** [comment]
Hmm this didn't happened before, it might be due to the recent  changes when getting the $filePath... Maybe we can quote fully the path or something before -Split ' '? Hmm... Idk, this is a tricky one... 

But if it is the split, the bug does not only affect CygWin, it affects the entire function. **This is a must fix soon**.

**Comment by HieiOne** [comment]
> Hmm this didn't happened before, it might be due to the recent  changes when getting the $filePath... Maybe we can quote fully the path or something before -Split ' '? Hmm... Idk, this is a tricky one... 

Lol nahh, it's because the path has spaces and since I play with double double quotes (instead of scaping it doesn't detect the full path correctly.

I use
```
""$filePath""
```

instead of
```
`'$filePath`'
```

That fixed the problem in a local beta I have.

Cheers

**Comment by alex13lopez** [comment]
Ah cool then, test it if it works without CygWin just to make sure.

**Comment by alex13lopez** [comment]
As I thought, this is a general bug, it also affects removeOldBackups. I'm working on it.
